name: Node.js CI

on: [push]  # Trigger the workflow on push events

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest Ubuntu environment

    steps:
      - uses: actions/checkout@v3  # Check out the repository code
      - uses: actions/setup-node@v3  # Set up Node.js
        with:
          node-version: 16  # Specify the Node.js version (adjust as needed)
      - run: npm install  # Install dependencies
      - run: node app.js  # Run your Node.js application 
